wars = {
	'REVOLUTIONARY WAR': 'RV',
	'REV WAR': 'RV',
	'RV': 'RV',
	'INDIAN WARS': 'IN',
	'IN': 'IN',
	'WAR OF 1812': '18',
	'MEXICAN WAR': 'MX',
	'MX': 'MX',
	'SPANISH AMERICAN WAR': 'SA',
	'SP-AM WAR': 'SA',
	'SA': 'SA',
	'MEXICAN BORDER': 'MB',
	'MEX BORDER': 'MB',
	'MB': 'MB',
	'WORLD WAR I': 'WI',
	'WW I': 'WI',
	'WWI': 'WI',
	'WI': 'WI',
	'WORLD WAR II': 'II',
	'WW II': 'II',
	'WWII': 'II',
	'II': 'II',
	'KOREA': 'KO',
	'KO': 'KO',
	'VIETNAM': 'VN',
	'VN': 'VN',
	'PERSIAN GULF': 'PG',
	'PG': 'PG',
	'DOMINICAN REPUBLIC': 'NL',
	'LEBANON': 'LB ',
	'LB': 'LB ',
	'GRENADA': 'GR',
	'GR': 'GR',
	'PANAMA': 'PA',
	'PA': 'PA',
	'SOMALIA': 'SM',
	'SM': 'SM',
	'KOSOVO': 'KS',
	'KS': 'KS',
	'BOSNIA': 'NL',
	'AFGHANISTAN': 'AF',
	'AF': 'AF',
	'PHILIPPINES': 'PH',
	'PH': 'PH',
	'IRAQ': 'IR',
	'IR': 'IR'
}